version: "3"
services:
  menu_master_app:
    build:
      context: .
      dockerfile: ./dockerfile.app
    volumes:
      - ./:/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=development
